-- Migration number: 0001 	 2025-11-07T13:59:47.585Z
CREATE TABLE resolvers (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  provider   VARCHAR(255) NOT NULL DEFAULT '',
  hostname   VARCHAR(255) NOT NULL DEFAULT '',
  alias      VARCHAR(255) NOT NULL DEFAULT '',
  ipv4       VARCHAR(45) NOT NULL DEFAULT '',
  is_deleted TINYINT NOT NULL DEFAULT 0,
  mtime      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ctime      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (provider, hostname)
);
